name: ci

on:
  push:

jobs:
  buildx:
    runs-on: ubuntu-latest
    env:          
      DOCKER_TARGET_PLATFORM: linux/amd64,linux/arm64/v8
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        if: success() 
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        if: success() 
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - 
        name: Build/push kafka docker image     
        if: success()      
        run: docker buildx build --platform ${DOCKER_TARGET_PLATFORM} --tag luivatra/kafka:latest --output type=image,push=true